### ISSUE TITLE
Deployed web pages cannot be accessed in China

### ISSUE THREAD

**Issue by zhaolu1206** [stephane-r/holoplay-pwa#22]
I really appreciate your support for this project. However, due to the internet censorship in China, even if the project is deployed on a VPS in the United States, accessing the website still requires the use of a VPN. Without a VPN, the website cannot be accessed. Are you asking if this project can automatically proxy access to YouTube?

**Comment by stephane-r** [comment]
Hello,

I don't know in detail about the Internet competition in China.

Currently, the public HoloPlay app is hosted via Vercel, which uses Amazon and therefore, in the US.

If the server is located in Europe, would that help?

Other information to take into account: certain Invidious instances are located in the US. You will need to manually select a server in another region via the settings page.

**Comment by zhaolu1206** [comment]
I have deployed my website on a VPS in the United States. The current situation is that if I try to access it directly using a network from China, the webpage can be opened, but the page fails to load completely and gets stuck in a loading loop. However, if I use a VPN or other proxy services, there are no issues with accessing the website.
![PXL_20230908_103324543](https://github.com/stephane-r/holoplay-pwa/assets/30510452/588fce43-9d5c-4d68-b279-e840fb689980)
![Uploading PXL_20230908_103402289.jpg…]()

**Comment by maboroshin** [comment]
https://docs.invidious.io/faq/#q-what-data-is-shared-with-youtube

Invidious doesn't use scripts on YouTube. However, it retrieves data directly from YouTube. Therefore, it may have been blocked by Chinese censorship.

Try accessing any instance of Invidious in your browser. You can turn on "Proxy videos" in preferences on Invidious instances. This way, Invidious may become a Proxy and avoid censorship. ([piped.video](https://piped.video/) doesn't have this problem because it acts as a proxy.) But if China bans that Invidious instance (or Piped instance), you won't be able to get YouTube data.
