### ISSUE TITLE
doesn't work all content

### ISSUE THREAD

**Issue by omagaditzx** [stephane-r/holoplay-pwa#96]
doesn't work video and audio clips of youtube

**Comment by stephane-r** [comment]
Hi @vlad-mark2020 

HoloPlay is currently no longer work. YouTube/Google has patched the latest Invidious workaround that we had in order to restore the video playback functionality.

See https://github.com/iv-org/invidious/issues/4734#issuecomment-2365205990

I will soon display a banner in the app to inform users. I hope that the Invidious team will succeed in finding the solution ❤️
